name: Auto Commit

on:
  schedule:
    - cron: '0,30 * * * *'  # Menjalankan commit otomatis setiap setengah jam (00 dan 30 menit setiap jam)
  push:
    branches:
      - main  # Ubah dengan nama cabang yang sesuai jika diperlukan

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "davidpangrib001"
          git config --global user.email "davidpangrib001@gmail.com"

      - name: Add current date and time to file.txt in WIB
        run: |
          # Menambahkan tanggal dan waktu saat ini dengan zona waktu WIB (UTC+7) ke dalam file.txt
          echo "$(TZ='Asia/Jakarta' date)" >> file.txt
          git add file.txt  # Menambahkan file.txt yang telah dimodifikasi

      - name: Commit changes
        run: |
          git commit -m "Auto commit: Update file.txt with current date and time (WIB)"
          git push

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GHT_TOKEN }}  # Token akses GitHub otomatis
        run: git push
