name: Auto Add Files

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-ip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add files
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M')
        curl -s https://api.myip.com > ./update/$TIMESTAMP.txt
 
    - name: Upload to GitHub
      run: |
        git config --global user.name "MyDapitt"
        git config --global user.email "dapitt@onee.eu.org"
        git add ./update/*.txt
        git commit -m "The files has been updated ($TIMESTAMP)"
        git push
